# Generated by Django 4.2.7 on 2025-05-27 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowlyne', '0002_alter_company_managers_alter_company_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic Plan (Free)'), ('standard', 'Standard Plan'), ('premium', 'Premium Plan')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('price_egp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_period', models.CharField(default='month', max_length=20)),
                ('search_ranking', models.CharField(max_length=200)),
                ('portfolio_view', models.CharField(max_length=200)),
                ('portfolio_uploads_per_month', models.IntegerField()),
                ('comments_view', models.CharField(max_length=200)),
                ('commission_discount', models.CharField(max_length=200)),
                ('business_insights', models.CharField(max_length=200)),
                ('support_level', models.CharField(max_length=200)),
                ('featured_on_homepage', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('advanced_analytics', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price_egp'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='current_plan',
            field=models.CharField(choices=[('basic', 'Basic Plan (Free)'), ('standard', 'Standard Plan'), ('premium', 'Premium Plan')], default='basic', help_text='Current subscription plan', max_length=20),
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renewal', models.BooleanField(default=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowlyne.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
