# Generated by Django 4.2.7 on 2025-05-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowlyne', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, help_text='Describe your company and what you do'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
