# Generated by Django 4.2.7 on 2025-06-06 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flowlyne', '0004_message_companyreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile App Development', 'Mobile App Development'), ('Digital Marketing', 'Digital Marketing'), ('Graphic Design', 'Graphic Design'), ('Business Consulting', 'Business Consulting'), ('Accounting & Finance', 'Accounting & Finance'), ('Content Creation', 'Content Creation'), ('UI/UX Design', 'UI/UX Design'), ('Video Production', 'Video Production'), ('IT Support', 'IT Support'), ('Other', 'Other')], max_length=50)),
                ('duration', models.CharField(blank=True, help_text='Estimated completion time', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-created_at'],
            },
        ),
    ]
